version: "3.3"

services:
  postgres:
    image: postgres:latest
    container_name: practice-psql
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-practice}
      POSTGRES_USER: ${POSTGRES_USER:-practice}
      POSTGRES_PASSWORD: "lgbtq+S"
    ports:
      - "3003:5432"
